<a href="https://colab.research.google.com/github/Roihan21/Machine-Learning-Projects/blob/main/Building_Good_Training_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Identifiying Missing Values in Tabular Data**

### **Create CSV data file**

In [3]:
import pandas as pd
from io import StringIO

csv_data = \
''''A,B,C,D
1.0, 2.0, 3.0, 4.0
5.0, 6.0,, 8.0
10.0,11.0,12.0,'''

csv_data

"'A,B,C,D\n1.0, 2.0, 3.0, 4.0\n5.0, 6.0,, 8.0\n10.0,11.0,12.0,"

### **Create Pandas DataFrame  from the `csv_data`**

In [5]:
df = pd.read_csv(StringIO(csv_data))
df

     'A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [6]:
df.isnull()

      'A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False  False  False   True

In [8]:
df.isnull().sum()

'A    0
B     0
C     1
D     1
dtype: int64

### **Convert dataframe into NumPy Array using the .values method on the df table**

In [10]:
import numpy as np

df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])