<a href="https://colab.research.google.com/github/RoihansLab/Machine-Learning-Projects/blob/main/06_hyperparameter_tuning_Random_Forest/hyperparameter_tuning_Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Hyperparametets for Machine Learning Model**

## **1. Make Syntetic Datasets**

### **1.1. Generate The Datasets**

In [46]:
from sklearn.datasets import make_classification

X ,y = make_classification(n_samples=200, n_redundant=0, n_classes=2, n_features=10, random_state=42)

### **1.2. Examine Data Dimension**

In [47]:
X.shape, y.shape

((200, 10), (200,))

In [48]:
import pandas as pd

In [49]:
import pandas as pd
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9
0,-1.065114,0.280920,0.529693,-0.398232,0.056650,-0.186971,-1.311836,-0.609512,-0.305225,0.010353
1,-0.546244,0.040911,0.579291,-2.895644,-0.015310,0.183360,-2.591042,-1.478912,0.391804,-0.576510
2,0.342725,-1.810057,1.329153,0.181484,0.642723,0.447709,1.117296,0.569767,0.456753,-0.082151
3,0.179894,-2.103379,0.940771,1.075866,-0.989628,-1.570501,-1.103589,0.918317,1.392002,-0.988591
4,0.413435,0.505716,1.496044,-2.441763,-1.778720,-1.244655,1.355638,-0.773789,1.876796,0.869606
...,...,...,...,...,...,...,...,...,...,...
195,1.066675,-1.408241,0.146714,1.689767,-0.167118,0.648710,0.507274,1.382159,1.169296,0.820482
196,-0.763259,-0.638870,-0.904317,-0.940574,0.259723,0.048085,0.570599,-1.627542,-1.804882,-0.662624
197,-1.062394,0.762274,2.589564,0.551293,1.187386,0.985730,0.452372,-0.187144,0.428307,-0.079641
198,-0.019420,0.186413,-1.067803,0.818552,-1.053682,-1.616311,-0.349317,0.799942,-0.303180,-0.223466
199,-0.098588,0.091482,0.287124,0.801218,0.953137,0.233216,1.410932,0.708214,0.018850,-1.090399

In [50]:
pd.DataFrame(y)

     0
0    0
1    0
2    1
3    1
4    0
..  ..
195  1
196  0
197  1
198  1
199  1

[200 rows x 1 columns]

# **2. Data Split(80/20)**

### **2.1 Data Split**

ratio for testing = 20%
ration for training = 80%

In [51]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

### **2.2. Examine Data Dimension**

#### **2.2.1 Examine Data Train Dimension**

as we can see the training sets in X variable has 160 row with 10 column for the X while there are 160 row with 1 column in y variable

In [52]:
X_train.shape, y_train.shape

((160, 10), (160,))

#### **2.2.2 Examine Data Test Dimension**

the testing sets has 40 rows and 10 column in X variable and 40 rows in 1 column y yvariable

In [53]:
X_test.shape, y_test.shape

((40, 10), (40,))

## **3. Building a Simple Machine Learning Model with Random Forest**

In [54]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf = RandomForestClassifier(n_estimators=100, max_features=100)

In [55]:
rf.fit(X_train, y_train)

RandomForestClassifier(max_features=100)

In [56]:
rf.score(X_test, y_test)

0.825

In [57]:
y_pred = rf.predict(X_test)

In [58]:
accuracy_score(y_pred, y_test)

0.825

In [59]:
y_pred, y_test

(array([0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
        1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1]),
 array([0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
        1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1]))

## **4. Hyperparametet Tuning**